kind: pipeline
name: default

steps:
    - name: build
      image: karalabe/xgo-latest 
      commands:
          - ci/install_gdal.sh
          - > 
            xgo
            --out tiffany-$DRONE_TAG
            --targets=linux/amd64
            -v
            .
    - name: publish
      image: plugins/github-release
      settings:
          api_key:
              from_secret: github_token 
          title: Release $DRONE_TAG
          files: tiffany*
      when:
          event: tag
          
